### ISSUE TITLE
FlagBrew

### ISSUE THREAD

**Issue by piepie62** [GriffinG1/FlagBot#17]
The tools repo is gone, having been split up, and all the other repos have been moved into FlagBrew's possession.

**Comment by GriffinG1** [comment]
Can you elaborate on the split, and provide links? Thanks

**Comment by SpiredMoth** [comment]
Updated links
- **PKSM**: https://github.com/FlagBrew/PKSM
- **Checkpoint**: https://github.com/FlagBrew/Checkpoint
- **Sharkive**: https://github.com/FlagBrew/Sharkive
- **QRaken**: https://github.com/FlagBrew/QRaken
- **2048**: https://github.com/FlagBrew/2048
- **Pickr**: https://github.com/FlagBrew/Pickr
- **PKSM-Scripts**: https://github.com/FlagBrew/PKSM-Scripts
- **serveLegality**: https://github.com/FlagBrew/serveLegality
- **servepkx**: https://github.com/FlagBrew/servepkx
- **Team List Filler**: https://github.com/FlagBrew/TeamListFiller

**Comment by GriffinG1** [comment]
Thanks
